kind: Deployment
apiVersion: apps/v1
metadata:
  name: backend
  labels:
    app: backend
    name: backend

spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
      task: backend
  template:
    metadata:
      labels:
        app: backend
        task: backend
    spec:
      containers:
        - name: backend
          image: xitrum/backend:3.0.1
          ports:
            - containerPort: 8000
              protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: backend
spec:
  ports:
    - name: backend
      port: 8000
      targetPort: 8000
  selector:
    app: backend
    task: backend
---
kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  name: backend
  annotations:
    kubernetes.io/ingress.class: traefik
    traefik.ingress.kubernetes.io/router.entrypoints: web

spec:
  rules:
    - host: devrel-500
      http:
        paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: backend
              port:
                number: 8000
